'use strict';
let seoDefaults={},seoRecords={},seoExtras=[],seoTab='pages',seoSelected='',seoQuery='',seoGroup='all';
async function seoInit(){[seoDefaults,seoExtras]=await Promise.all([fetch('./seo-defaults.json').then(r=>r.json()),fetch('./seo-extra-pages.json').then(r=>r.json())]);}
async function seoLoad(){const [records,extra]=await Promise.all([cmsRequest('/rest/v1/cms_seo_sites?select=*'),cmsRequest('/rest/v1/cms_pages?id=like.pay-blog-*&select=id,draft_content,published_at')]);seoRecords=Object.fromEntries(records.map(r=>[r.site,r]));seoExtras=seoExtras.map(p=>{const row=extra.find(r=>r.id===p.id);return row?{...p,...row.draft_content,publishedAt:row.published_at}:p;});}
const seoSiteId=()=>getSite(route.site)?route.site:state.sites[0].id;
const seoConfig=id=>clone(seoRecords[id]?.draft_config||seoDefaults[id]);
function seoAvailablePages(id){return sitePages(id).concat(seoExtras.filter(p=>p.site===id));}
function seoPage(id){const p=getPage(id)||seoExtras.find(p=>p.id===id);return {...p,seoTitle:p.seoTitle||catalog.pages.find(x=>x.id===id)?.seoTitle,seoDescription:p.seoDescription||p.description,seo:{...catalog.pages.find(x=>x.id===id)?.seo,...p.seo}};}
function seoChecks(p,s){const m=CredMaisSEO.meta(s,p),text=[p.title,p.description,...p.sections.flatMap(x=>[x.title,x.text,...(x.items||[]).flatMap(i=>[i.title,i.text])])].join(' ').toLocaleLowerCase('pt-BR'),term=p.seo?.focusKeyword?.trim().toLocaleLowerCase('pt-BR');return [
 ['Título descritivo',m.title.length>=25&&m.title.length<=65,'Referência editorial: 25–65 caracteres. O Google pode reescrever o título.'],
 ['Descrição da página',m.description.length>=80&&m.description.length<=170,'Referência editorial: 80–170 caracteres, sem promessas não confirmadas.'],
 ['URL canônica',Boolean(CredMaisSEO.https(m.url)),'Uma URL principal para evitar versões concorrentes.'],
 ['Imagem de compartilhamento',Boolean(m.image),'Aparece em prévias de redes sociais e aplicativos.'],
 ['Termo principal no conteúdo',Boolean(term&&text.includes(term)),'O termo deve fazer sentido no texto visível, sem repetição artificial.'],
 ['Imagens com descrição',p.sections.filter(x=>x.visible!==false&&x.imageId&&x.type!=='original').every(x=>x.alt?.trim()),'Confira também as imagens nativas na revisão visual da página.'],
 ['Título exclusivo',!state.pages.some(x=>x.site===p.site&&x.id!==p.id&&CredMaisSEO.meta(s,seoPage(x.id)).title===m.title),'Cada página deve responder a uma intenção diferente.']
 ];}
function seoPreview(p,s){const m=CredMaisSEO.meta(s,p);return `<div class="seo-search-preview"><span>${esc(s.name)}</span><small>${esc(m.url)}</small><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p></div><small class="seo-caption">Prévia ilustrativa. O Google decide a apresentação final.</small>`;}
function seoView(){const id=seoSiteId(),s=seoConfig(id),pages=seoAvailablePages(id);if(!pages.some(p=>p.id===seoSelected))seoSelected=pages[0].id;const p=seoPage(seoSelected),record=seoRecords[id];return heading('Presença no Google','Configuração técnica, conteúdo e descoberta para cada marca.')+tabs('seo',id,false,false)+`<div class="seo-context"><div><b>${esc(s.origin)}</b><span>${record?.published_at?'SEO publicado em '+dateFormat(record.published_at):'Configuração inicial pronta'}</span></div><a class="button small" href="https://search.google.com/search-console" target="_blank" rel="noopener noreferrer">${icon('external')} Search Console</a></div><nav class="seo-nav" aria-label="Áreas de SEO">${[['pages','Páginas'],['keywords','Palavras-chave'],['technical','Rastreamento e marca'],['files','Arquivos e revisão']].map(([key,label])=>`<button data-seo="tab" data-id="${key}" class="${seoTab===key?'active':''}">${label}</button>`).join('')}</nav>${id==='pay'?notice('CredMais Pay tem hospedagem externa. O painel salva e publica a configuração; os arquivos iniciais e as novas versões devem ser enviados à equipe de hospedagem.'):''}${seoTab==='pages'?seoPages(p,s,pages):seoTab==='keywords'?seoKeywords(s,pages):seoTab==='technical'?seoTechnical(s):seoFiles(s,pages)}`;}
function seoPages(p,s,pages){const m=CredMaisSEO.meta(s,p),checks=seoChecks(p,s);return `<div class="seo-layout"><section class="seo-card"><form id="seo-page-form" data-page="${p.id}"><label class="field"><span>Página</span><select id="seo-page-select">${pages.map(x=>`<option value="${x.id}" ${p.id===x.id?'selected':''}>${esc(x.name)} · ${esc(x.path)}</option>`).join('')}</select></label>${field('Título na busca','seoTitle',m.title,'input','Um título próprio para esta página.','maxlength="120" required')}${field('Descrição na busca','seoDescription',m.description,'textarea','Resuma o conteúdo e o próximo passo.','maxlength="350" required')}${field('Palavra-chave principal','focusKeyword',p.seo?.focusKeyword||'','input','Use uma intenção de busca por página.','maxlength="120"')}${field('URL canônica personalizada','canonical',p.seo?.canonical||'','input','Deixe vazio para usar '+esc(s.origin+p.path)+'.','type="url" placeholder="https://..."')}${field('Imagem para compartilhamento','image',p.seo?.image||'','input','Vazio usa a imagem padrão do site. HTTPS, preferencialmente 1200 × 630 px.','type="url" placeholder="https://..."')}${field('Descrição da imagem','imageAlt',p.seo?.imageAlt||s.name,'input','','maxlength="200"')}<label class="seo-toggle"><input name="noindex" type="checkbox" ${p.seo?.noindex?'checked':''}>Não indexar esta página no Google</label><label class="seo-toggle"><input name="nofollow" type="checkbox" ${p.seo?.nofollow?'checked':''}>Não seguir os links desta página</label><div class="form-actions"><button type="button" class="button" data-seo="save-page">Salvar rascunho</button><button type="button" class="button primary" data-seo="publish-page">Publicar SEO da página</button></div></form></section><aside><section class="seo-card"><h2>Como pode aparecer na busca</h2><div id="seo-live-preview">${seoPreview(p,s)}</div></section><section class="seo-card"><h2>Revisão editorial</h2><p>Estas verificações analisam a configuração. Não medem posição, tráfego ou indexação real.</p><ul class="seo-checks">${checks.map(([label,ok,help])=>`<li>${icon(ok?'check':'help')}<div><b>${esc(label)}</b><span>${esc(help)}</span></div><small>${ok?'Configurado':'Revisar'}</small></li>`).join('')}</ul></section>${p.seoOnlyPage?'':`<a class="button" href="#page-edit?id=${p.id}">${icon('edit')} Editar conteúdo e imagens</a>`}</aside></div>`;}
function seoKeywords(s,pages){const words=s.keywords||[],filtered=words.filter(w=>(seoGroup==='all'||w.group===seoGroup)&&w.term.toLocaleLowerCase('pt-BR').includes(seoQuery.toLocaleLowerCase('pt-BR')));return `<section class="seo-card"><div class="section-heading"><div><h2>${words.length} termos para planejar o conteúdo</h2><p>Pauta inicial por intenção. Volume e dificuldade não foram pesquisados. Valide os termos no Search Console.</p></div><button class="button small" data-seo="export-keywords">${icon('download')} Exportar CSV</button></div><div class="seo-word-toolbar"><label class="field"><span>Buscar termo</span><input id="seo-word-search" value="${esc(seoQuery)}" placeholder="Ex.: recebíveis"></label><label class="field"><span>Tema</span><select id="seo-word-group"><option value="all">Todos</option>${[...new Set(words.map(w=>w.group))].map(g=>`<option ${seoGroup===g?'selected':''}>${esc(g)}</option>`).join('')}</select></label><button class="button" data-seo="add-keyword">${icon('plus')} Adicionar termo</button></div><p class="seo-caption">Use os termos naturalmente nos textos, títulos, links e descrições de imagem. A meta tag keywords não é usada pelo Google.</p><div class="seo-table-wrap"><table class="seo-table"><thead><tr><th>Palavra-chave</th><th>Tema</th><th>Página de destino</th><th>Planejamento</th><th><span class="sr-only">Ação</span></th></tr></thead><tbody>${filtered.map(w=>{const i=words.indexOf(w);return `<tr><td><input aria-label="Termo" data-word="${i}" data-key="term" value="${esc(w.term)}" maxlength="120"></td><td><input aria-label="Tema" data-word="${i}" data-key="group" value="${esc(w.group)}" maxlength="60"></td><td><select aria-label="Página de destino" data-word="${i}" data-key="path">${pages.map(p=>`<option value="${p.path}" ${p.path===w.path?'selected':''}>${esc(p.name)}</option>`).join('')}</select></td><td><select aria-label="Planejamento" data-word="${i}" data-key="status"><option value="planned" ${w.status==='planned'?'selected':''}>Planejado</option><option value="writing" ${w.status==='writing'?'selected':''}>Em produção</option><option value="published" ${w.status==='published'?'selected':''}>Conteúdo publicado</option></select></td><td><button class="icon-button" data-seo="remove-keyword" data-id="${i}" aria-label="Remover termo">${icon('trash')}</button></td></tr>`;}).join('')}</tbody></table></div>${!filtered.length?'<p>Nenhum termo encontrado.</p>':''}<div class="form-actions"><button class="button primary" data-seo="save-keywords">Salvar planejamento</button><span class="seo-caption">A lista fica apenas no painel.</span></div></section>`;}
function seoTechnical(s){return `<div class="seo-layout"><section class="seo-card"><h2>Rastreamento e identidade</h2><form id="seo-site-form">${field('Nome público da marca','name',s.name,'input','','required maxlength="100"')}<label class="field"><span>Domínio principal</span><input value="${esc(s.origin)}" readonly><small>Domínio usado nas URLs canônicas e no sitemap.</small></label>${field('Descrição da marca','description',s.description||'','textarea','','maxlength="350"')}${field('Logo oficial','logo',s.logo||'','input','URL pública HTTPS. Não use símbolos de marcas diferentes.','type="url"')}${field('Imagem padrão de compartilhamento','socialImage',s.socialImage||'','input','Use uma imagem da marca, de preferência 1200 × 630 px.','type="url"')}${field('Verificação do Google Search Console','verification',s.verification||'','input','Cole somente o valor content fornecido pelo Google, sem a tag HTML.','maxlength="500"')}${field('Perfis oficiais, um por linha','sameAs',(s.sameAs||[]).join('\n'),'textarea','Somente perfis desta marca.','maxlength="3000"')}${field('Caminhos adicionais para bloquear no robots.txt','disallow',(s.disallow||[]).join('\n'),'textarea','Um caminho por linha, começando com /. Bloquear rastreamento não remove uma página já indexada.','maxlength="3000"')}<label class="seo-toggle"><input name="indexing" type="checkbox" ${s.indexing!==false?'checked':''}>Permitir indexação das páginas públicas</label><div class="form-actions"><button type="button" class="button" data-seo="save-site">Salvar rascunho</button><button type="button" class="button primary" data-seo="publish-site">Publicar SEO do site</button></div></form></section><aside><section class="seo-card"><h2>Informação verificável</h2><p>Os dados estruturados identificam a marca, o site, a página, os caminhos de navegação e os quatro serviços da Securitizadora.</p><p>Sem avaliações, números de clientes, endereço ou CNPJ inventados. Você poderá incluir dados cadastrais quando forem confirmados.</p><a href="https://search.google.com/test/rich-results" target="_blank" rel="noopener noreferrer" class="button small">Validar dados estruturados ${icon('external')}</a></section><section class="seo-card"><h2>Medir o que acontece</h2><ol class="seo-next"><li>Adicione a propriedade no Search Console.</li><li>Copie a verificação para o campo ao lado e publique.</li><li>Informe <b>sitemap.xml</b> no relatório de sitemaps.</li><li>Use Inspeção de URL para revisar páginas reais.</li><li>Acompanhe consultas, cliques e impressões antes de ajustar a pauta.</li></ol><p>O painel não exibe métricas do Google sem uma integração autorizada.</p></section></aside></div>`;}
function seoFiles(s,pages){const robots=CredMaisSEO.robots(s),sitemap=CredMaisSEO.sitemap(s,pages.map(p=>seoPage(p.id)));return `<div class="seo-layout"><section class="seo-card"><h2>robots.txt</h2><p>Arquivo gerado a partir das preferências do site.</p><pre class="seo-code">${esc(robots)}</pre><div class="heading-actions"><button class="button small" data-seo="download-robots">${icon('download')} Baixar robots.txt</button><a href="${s.origin}/robots.txt" target="_blank" rel="noopener noreferrer" class="button small">Abrir publicado ${icon('external')}</a></div><h2 class="seo-subheading">Sitemap</h2><p>${pages.filter(p=>CredMaisSEO.indexable(s,seoPage(p.id))).length} páginas públicas no catálogo. Páginas sem indexação e URLs externas são excluídas.</p><pre class="seo-code">${esc(sitemap)}</pre><div class="heading-actions"><button class="button small" data-seo="download-sitemap">${icon('download')} Baixar sitemap.xml</button><a href="${s.origin}/sitemap.xml" target="_blank" rel="noopener noreferrer" class="button small">Abrir publicado ${icon('external')}</a></div></section><aside><section class="seo-card"><h2>Revisão antes de divulgar</h2><ul class="seo-next"><li>Títulos e descrições únicos por página.</li><li>Uma intenção de busca por conteúdo.</li><li>Hierarquia de títulos legível e links úteis.</li><li>Texto alternativo de imagens relevante.</li><li>Imagens WebP e tamanho adequado para cada tela.</li><li>Site HTTPS e páginas de administração fora da busca.</li><li>Formulários e navegação acessíveis no celular.</li><li>Informações financeiras claras e verificáveis.</li></ul><p>Otimização técnica facilita descoberta; relevância e qualidade do conteúdo também influenciam os resultados.</p></section><section class="seo-card"><h2>Entrega e validação</h2><button class="button" data-seo="download-config">${icon('download')} Exportar configuração SEO</button><p>Inclui as preferências publicadas e os metadados por página. Não contém tokens ou dados dos formulários.</p><a class="button small" href="https://pagespeed.web.dev/analysis?url=${encodeURIComponent(s.origin)}" target="_blank" rel="noopener noreferrer">PageSpeed Insights ${icon('external')}</a></section></aside></div>`;}
function seoReadPage(validate=true){const form=$('#seo-page-form');if(validate&&!form.reportValidity())throw Error('Revise os campos da página.');const data=new FormData(form),p=seoPage(form.dataset.page);p.seoTitle=String(data.get('seoTitle')).trim();p.seoDescription=String(data.get('seoDescription')).trim();p.seo={...p.seo,...Object.fromEntries(['focusKeyword','canonical','image','imageAlt'].map(k=>[k,String(data.get(k)||'').trim()])),noindex:data.has('noindex'),nofollow:data.has('nofollow')};for(const key of ['canonical','image'])if(p.seo[key]&&!CredMaisSEO.https(p.seo[key]))throw Error('Use URLs HTTPS válidas.');return p;}
function seoReadSite(){const form=$('#seo-site-form');if(!form.reportValidity())throw Error('Revise os campos do site.');const data=new FormData(form),s=seoConfig(seoSiteId());for(const key of ['name','description','logo','socialImage','verification'])s[key]=String(data.get(key)||'').trim();s.indexing=data.has('indexing');s.sameAs=String(data.get('sameAs')).split('\n').map(v=>v.trim()).filter(Boolean);s.disallow=String(data.get('disallow')).split('\n').map(v=>v.trim()).filter(Boolean);if([s.logo,s.socialImage,...s.sameAs].some(v=>v&&!CredMaisSEO.https(v)))throw Error('Use URLs HTTPS válidas para imagens e perfis.');if(s.disallow.some(v=>!v.startsWith('/')||v.startsWith('//')||/[\s?#]/.test(v)))throw Error('Informe caminhos válidos começando com /.');return s;}
function seoDownload(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function seoSaveConfig(config,publish=false){const id=seoSiteId(),old=seoRecords[id],at=new Date().toISOString(),record={site:id,draft_config:config,updated_at:at,...(publish?{published_config:Object.fromEntries(Object.entries(config).filter(([k])=>k!=='keywords')),published_at:at}:{})};await cmsRequest('/rest/v1/cms_seo_sites',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(record)});seoRecords[id]={...old,...record};}
async function seoSavePage(p,publish=false){await cmsSaving.get(p.id);const records=await cmsRequest('/rest/v1/cms_pages?id=eq.'+encodeURIComponent(p.id)+'&select=draft_content,published_content');const row=records[0];if(!row)throw Error('Página não encontrada.');const seo={seo:p.seo,seoTitle:p.seoTitle,seoDescription:p.seoDescription},at=new Date().toISOString(),draft={...row.draft_content,...seo,updatedAt:at};const published=row.published_content?{...row.published_content,...seo}:{id:p.id,path:p.path,name:p.name,...seo,seoOnly:true};await cmsRequest('/rest/v1/cms_pages?id=eq.'+encodeURIComponent(p.id),{method:'PATCH',body:JSON.stringify({draft_content:draft,updated_at:at,...(publish?{published_content:published,published_at:at}:{})})});Object.assign(getPage(p.id)||seoExtras.find(x=>x.id===p.id),seo,{updatedAt:at,...(publish?{publishedAt:at}:{})});persist();}
document.addEventListener('click',async event=>{const control=event.target.closest('[data-seo]');if(!control)return;const action=control.dataset.seo,id=seoSiteId(),config=seoConfig(id);control.disabled=true;try{
 if(action==='tab'){seoTab=control.dataset.id;render();}
 else if(['save-page','publish-page'].includes(action)){await seoSavePage(seoReadPage(),action==='publish-page');toast(action==='publish-page'?'SEO da página publicado.':'Rascunho de SEO salvo.');render();}
 else if(['save-site','publish-site'].includes(action)){const s=seoReadSite();if(action==='publish-site'&&!s.indexing&&!confirm('Isso impede a indexação de todas as páginas deste site. Publicar mesmo assim?'))return;await seoSaveConfig(s,action==='publish-site');toast(action==='publish-site'?'SEO do site publicado.':'Rascunho de SEO salvo.');render();}
 else if(action==='save-keywords'){await seoSaveConfig(config);toast('Planejamento de palavras-chave salvo.');}
 else if(action==='add-keyword'){config.keywords.push({term:'Novo termo',group:'Novo tema',path:'/',status:'planned'});seoRecords[id]={...seoRecords[id],draft_config:config};seoQuery='';seoGroup='all';render();}
 else if(action==='remove-keyword'){config.keywords.splice(Number(control.dataset.id),1);seoRecords[id]={...seoRecords[id],draft_config:config};render();}
 else if(action==='export-keywords'){const quote=v=>'"'+String(v||'').replace(/"/g,'""')+'"',safe=v=>/^[=+@\-\t\r]/.test(v)?"'"+v:v;seoDownload(id+'-palavras-chave.csv','\uFEFF'+[['Termo','Tema','Página','Planejamento'],...config.keywords.map(w=>[w.term,w.group,w.path,w.status])].map(r=>r.map(v=>quote(safe(v))).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
 else if(action==='download-robots')seoDownload('robots.txt',CredMaisSEO.robots(config));
 else if(action==='download-sitemap')seoDownload('sitemap.xml',CredMaisSEO.sitemap(config,seoAvailablePages(id).map(p=>seoPage(p.id))),'application/xml');
 else if(action==='download-config'){const rows=await cmsRequest('/rest/v1/cms_pages?site=eq.'+id+'&select=id,path,published_content');seoDownload(id+'-seo.json',JSON.stringify({site:seoRecords[id]?.published_config||seoDefaults[id],pages:rows.map(r=>{const p=seoPage(r.id),data=r.published_content||p;return {id:r.id,path:r.path,name:p.name,seo:data.seo,seoTitle:data.seoTitle,seoDescription:data.seoDescription};})},null,2),'application/json');}
 }catch(error){toast(error.message,'help');}finally{control.disabled=false;}});
document.addEventListener('change',event=>{const e=event.target;if(e.id==='seo-page-select'){seoSelected=e.value;render();}if(e.id==='seo-word-group'){seoGroup=e.value;render();}if(e.dataset.word!==undefined){const id=seoSiteId(),config=seoConfig(id),w=config.keywords[Number(e.dataset.word)];if(w){w[e.dataset.key]=e.value.trim();seoRecords[id]={...seoRecords[id],draft_config:config};}}});
document.addEventListener('input',event=>{if(event.target.id==='seo-word-search'){seoQuery=event.target.value;const selection=event.target.selectionStart;render();$('#seo-word-search').focus();$('#seo-word-search').setSelectionRange(selection,selection);}if(event.target.closest('#seo-page-form')){try{$('#seo-live-preview').innerHTML=seoPreview(seoReadPage(false),seoConfig(seoSiteId()));}catch{}}});
